### PR TITLE
Use cache to Improve performance

### PR DESCRIPTION
**Pull request by flier268**

### CODE REVIEW

**Comment by flier268** [comment]
By the way, "gradle.properties" and other file does not push to git?
I have a hard time compiling the project

**Comment by DenuxPlays** [comment]
Is this ever gonna be merged/finished?
I think the mod could really benefit from a performance improvement

**Comment by tom5454** [comment]
A similar system was added in the 1.21 update,

**Comment by masuteri** [comment]
What about 1.20.1? A huge amount of fabric mods stay on that version.

**Pull request closed without merging**
